name: devops test
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest    ## 작업을 어디다가 실행할 것인지

    steps:    ## 어떤 작업을 실행할 것인지
      - name: get code from github
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SECRET }}
          port: ${{ secrets.PORT }}
          script: |
            echo test > /tmp/abcd
      

    
